"""empty message

Revision ID: 284663db5607
Revises: 
Create Date: 2022-04-11 11:53:29.503561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284663db5607'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
